// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taskboard.EntityFrameworkCore.Data;

#nullable disable

namespace Taskboard.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(TaskboardDbContext))]
    [Migration("20260921141558_AddAgentRunEvents")]
    partial class AddAgentRunEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Taskboard.Domain.Agents.AgentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stream")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AgentLogs", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Agents.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModelTier")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("AgentRuns", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Agents.AgentRunEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentEventId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ScopeId", "Kind");

                    b.HasIndex("ScopeKind", "ScopeId", "Sequence")
                        .IsUnique();

                    b.ToTable("AgentRunEvents", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AgentPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgentType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentType")
                        .IsUnique();

                    b.ToTable("AgentPreferences", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("message");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("AiChatEvents", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("AiChatRuns", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatThread", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("assistant");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasoningEffort")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryFullName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sandbox")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkspacePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiChatThreads", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.CliMetrics.CliDailyUsageAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MessagesCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokensCached")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokensInput")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TokensOutput")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Day")
                        .IsUnique();

                    b.ToTable("CliDailyUsageAggregates", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.CliMetrics.CliMetricSource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("RowCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaFingerprint")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WatermarkCursor")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "SourceName", "ResolvedPath")
                        .IsUnique();

                    b.ToTable("CliMetricSources", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.CliMetrics.CliSessionMetric", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IngestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TokensCached")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TokensInput")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TokensOutput")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("CliSessionMetrics", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.ConfigurationOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ConfigurationOverrides", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.ModelPriceRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CacheReadPer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CacheWritePer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InputPer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelPattern")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutputPer1M")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModelPattern")
                        .IsUnique();

                    b.ToTable("ModelPriceRates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            CacheReadPer1M = 0.30m,
                            CacheWritePer1M = 3.75m,
                            InputPer1M = 3.00m,
                            ModelPattern = "claude-3-7-sonnet",
                            OutputPer1M = 15.00m,
                            Provider = "anthropic"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            CacheReadPer1M = 0.30m,
                            CacheWritePer1M = 3.75m,
                            InputPer1M = 3.00m,
                            ModelPattern = "claude-sonnet-4",
                            OutputPer1M = 15.00m,
                            Provider = "anthropic"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            CacheReadPer1M = 0.10m,
                            CacheWritePer1M = 1.25m,
                            InputPer1M = 1.00m,
                            ModelPattern = "claude-haiku-4",
                            OutputPer1M = 5.00m,
                            Provider = "anthropic"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            CacheReadPer1M = 1.50m,
                            CacheWritePer1M = 18.75m,
                            InputPer1M = 15.00m,
                            ModelPattern = "claude-opus-4",
                            OutputPer1M = 75.00m,
                            Provider = "anthropic"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            CacheReadPer1M = 0.125m,
                            CacheWritePer1M = 1.25m,
                            InputPer1M = 1.25m,
                            ModelPattern = "gpt-5",
                            OutputPer1M = 10.00m,
                            Provider = "openai"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            CacheReadPer1M = 0.025m,
                            CacheWritePer1M = 0.25m,
                            InputPer1M = 0.25m,
                            ModelPattern = "gpt-5-mini",
                            OutputPer1M = 2.00m,
                            Provider = "openai"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000007"),
                            CacheReadPer1M = 0.50m,
                            CacheWritePer1M = 2.00m,
                            InputPer1M = 2.00m,
                            ModelPattern = "gpt-4.1",
                            OutputPer1M = 8.00m,
                            Provider = "openai"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000008"),
                            CacheReadPer1M = 0.07m,
                            CacheWritePer1M = 0.27m,
                            InputPer1M = 0.27m,
                            ModelPattern = "deepseek-chat",
                            OutputPer1M = 1.10m,
                            Provider = "deepseek"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000009"),
                            CacheReadPer1M = 0.14m,
                            CacheWritePer1M = 0.55m,
                            InputPer1M = 0.55m,
                            ModelPattern = "deepseek-reasoner",
                            OutputPer1M = 2.19m,
                            Provider = "deepseek"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000010"),
                            CacheReadPer1M = 0.125m,
                            CacheWritePer1M = 1.25m,
                            InputPer1M = 1.25m,
                            ModelPattern = "gemini-2.5-pro",
                            OutputPer1M = 10.00m,
                            Provider = "google"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000011"),
                            CacheReadPer1M = 0.03m,
                            CacheWritePer1M = 0.30m,
                            InputPer1M = 0.30m,
                            ModelPattern = "gemini-2.5-flash",
                            OutputPer1M = 2.50m,
                            Provider = "google"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000012"),
                            CacheReadPer1M = 0.30m,
                            CacheWritePer1M = 3.75m,
                            InputPer1M = 3.00m,
                            ModelPattern = "*",
                            OutputPer1M = 15.00m,
                            Provider = "*"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000013"),
                            CacheReadPer1M = 0m,
                            CacheWritePer1M = 0m,
                            InputPer1M = 0m,
                            ModelPattern = "free-stack",
                            OutputPer1M = 0m,
                            Provider = "omniroute"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000014"),
                            CacheReadPer1M = 0m,
                            CacheWritePer1M = 0m,
                            InputPer1M = 0m,
                            ModelPattern = "auto/best-free",
                            OutputPer1M = 0m,
                            Provider = "omniroute"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000015"),
                            CacheReadPer1M = 0.30m,
                            CacheWritePer1M = 3.75m,
                            InputPer1M = 3.00m,
                            ModelPattern = "auto/best-coding",
                            OutputPer1M = 15.00m,
                            Provider = "omniroute"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000016"),
                            CacheReadPer1M = 1.50m,
                            CacheWritePer1M = 18.75m,
                            InputPer1M = 15.00m,
                            ModelPattern = "Opus",
                            OutputPer1M = 75.00m,
                            Provider = "omniroute"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000017"),
                            CacheReadPer1M = 0.07m,
                            CacheWritePer1M = 0.27m,
                            InputPer1M = 0.27m,
                            ModelPattern = "DeepSeek",
                            OutputPer1M = 1.10m,
                            Provider = "omniroute"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000018"),
                            CacheReadPer1M = 0m,
                            CacheWritePer1M = 0m,
                            InputPer1M = 0m,
                            ModelPattern = "mimo-v2.5-free",
                            OutputPer1M = 0m,
                            Provider = "opencode"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000019"),
                            CacheReadPer1M = 0m,
                            CacheWritePer1M = 0m,
                            InputPer1M = 0m,
                            ModelPattern = "hy3-free",
                            OutputPer1M = 0m,
                            Provider = "opencode"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000020"),
                            CacheReadPer1M = 0m,
                            CacheWritePer1M = 0m,
                            InputPer1M = 0m,
                            ModelPattern = "muse-spark-1.2-contributor-free",
                            OutputPer1M = 0m,
                            Provider = "opencode"
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000021"),
                            CacheReadPer1M = 0.03m,
                            CacheWritePer1M = 0.30m,
                            InputPer1M = 0.30m,
                            ModelPattern = "gemini-3.8-flash",
                            OutputPer1M = 2.50m,
                            Provider = "google"
                        });
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.PipelineExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BudgetCapUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialPrompt")
                        .IsRequired()
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryFullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PipelineExecutions", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.PipelineStageExecution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdjustedPrompt")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("Agent")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalComment")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOn")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("HandoffSummary")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId", "StageKey")
                        .IsUnique();

                    b.ToTable("PipelineStageExecutions", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.ProjectMemoryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryFullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryFullName");

                    b.ToTable("ProjectMemoryItems", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.RunCostMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("BudgetCapUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAtUtc");

                    b.HasIndex("RunId");

                    b.HasIndex("AgentType", "ModelName");

                    b.ToTable("RunCostMetrics", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.VerificationReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CoveragePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorktreePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("VerificationReports", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.WorktreeSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetainOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("WorktreeSessions", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubToken")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Issues.IssueHistoryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueHistoryEvents", (string)null);
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatEvent", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.AiChatThread", null)
                        .WithMany("Events")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatRun", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.AiChatThread", null)
                        .WithMany("Runs")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.PipelineStageExecution", b =>
                {
                    b.HasOne("Taskboard.Domain.Entities.Harness.PipelineExecution", null)
                        .WithMany("Stages")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.AiChatThread", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Taskboard.Domain.Entities.Harness.PipelineExecution", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
